import dash
from dash import html

dash.register_page(__name__, path='/', name="Introduction 😃")

####################### PAGE LAYOUT #############################
layout = html.Div(children=[
    html.Div(children=[
        html.H2("Project Report: Data Cleaning and Visualization of Employment Dataset"),
        html.Br(),
        html.H3("Overview"),
        "This project involves cleaning, analyzing, and visualizing a dataset related to university graduates, their fields of study, and employment outcomes such as job offers, salaries, and internships.",
        "The aim is to derive meaningful insights from the data and prepare it for further analysis or modeling.",
    ]),
    html.Div(children=[
        html.Br(),
        html.H3("Data Description"),
        html.B("Student_ID"),
        html.Br(),
        html.B("Age"),
        html.Br(),
        html.B("Gender"),
        html.Br(),
        html.B("High_School_GPA"),
        html.Br(),
        html.B("SAT_Score"),
        html.Br(),
        html.B("University_Ranking"),
        html.Br(),
        html.B("University_GPA"),
        html.Br(),
        html.B("Field_of_Study"),
        html.Br(),
        html.B("Internships_Completed"),
        html.Br(),
        html.B("Projects_Completed"),
        html.Br(),
        html.B("Certification"),
        html.Br(),
        html.B("Soft_Skills_Score"),
        html.Br(),
        html.B("Networking_Score"),
        html.Br(),
        html.B("Job_Offers"),
        html.Br(),
        html.B("Starting_Salary"),
        html.Br(),
        html.B("Career_Satisfaction"),
        html.Br(),
        html.B("Years_to_Promotion"),
        html.Br(),
        html.B("Current_Job_Level"),
        html.Br(),
        html.B("Work_Life_Balance"),
        html.Br(),
        html.B("Entrepreneurship"),
        html.Br(),
        html.B("Birthdate"),
        html.Br(),
        "The dataset contains missing values, inconsistent labels, and formatting issues.",
        html.Br(),html.Br(),
    ]),
    html.Div(children=[
        html.H3("Goal of the Project"),
        html.Div("1. Clean the data to handle missing values and inconsistencies."),
        html.Div("2. Prepare the data for visualization by ensuring correct data types and uniform formatting."),
        html.Div("3. Visualize the data to identify trends and patterns related to job offers, salaries, and experience."),
        html.Div("4. Generate insights that can help understand employment trends across different fields and job levels."),
        html.Br(),html.Br(),
    ]),
    html.Div(children=[
        html.H3("Data Cleaning Steps"),
        "The cleaning process was performed in the clean_data() function and included:",
        html.Div("Loading the dataset using pandas.",style={'marginLeft': '20px'}),
        html.Div("Inspecting basic statistics and structure of the dataset.",style={'marginLeft': '20px'}),
        html.Div("Handling missing values:",style={'marginLeft': '20px'}),
        html.Div("i. Filled missing Age and University_GPA with the column mean.",style={'marginLeft': '30px'}),
        html.Div("ii. Filled missing Gender, Field_of_Study, and Current_Job_Level with the mode.",style={'marginLeft': '30px'}),
        html.Div("Cleaning the Starting_Salary column:",style={'marginLeft': '20px'}),
        html.Div("i. Removed dollar signs ($) and commas.",style={'marginLeft': '30px'}),
        html.Div("ii. Converted the column to a numeric data type.",style={'marginLeft': '30px'}),
        html.Div("Standardizing field names:",style={'marginLeft': '20px'}),
        html.Div("i. Replaced \"Engineer\" with \"Engineering\" in the Field_of_Study column.",style={'marginLeft': '30px'}),
        html.Div("Capping extreme salary values:",style={'marginLeft': '20px'}),
        html.Div("i. Replaced salaries above the 95th percentile with the cap to reduce outlier impact.",style={'marginLeft': '30px'}),
        html.Br(),html.Br(),
    ]),
    html.Div(children=[
        html.H3("Data Visualization"),
        "The visualize_data() function provides multiple visualizations to explore the dataset:",
        html.Div("1. Bar Chart: Job Offers by Field and Gender",style={'marginLeft': '20px'}),
        html.Div("Shows which fields have the most job offers and the gender distribution in those fields.",style={'marginLeft': '30px'}),
        html.Div("2. Boxplot: Salary by Field and Job Level",style={'marginLeft': '20px'}),
        html.Div("Reveals the salary distribution across different fields of study and current job levels.",style={'marginLeft': '30px'}),
        html.Div("Highlights median, spread, and outliers.",style={'marginLeft': '30px'}),
        html.Div("3. Pie Charts: Projects and Internships by Field",style={'marginLeft': '20px'}),
        html.Div("Visual representation of project and internship experience distribution across fields.",style={'marginLeft': '30px'}),
        html.Div("4. Funnel Chart: Distribution Across Job Levels",style={'marginLeft': '20px'}),
        html.Div("Visualizes the count of individuals at each job level in a funnel format.",style={'marginLeft': '30px'}),
        html.Div("Helps understand career progression and role distribution.",style={'marginLeft': '30px'}),
        html.Br(),html.Br(),
    ]),
    html.Div(children=[
        html.H3("Insights and Observations"),
        html.Div("1. Fields like Engineering and Business tend to receive higher numbers of job offers.",style={'marginLeft': '30px'}),
        html.Div("2. Starting salaries vary significantly with job level and field.",style={'marginLeft': '30px'}),
        html.Div("3. Internships and project experience are not evenly distributed some fields offer more experiential learning.",style={'marginLeft': '30px'}),
        html.Div("4. A majority of individuals seem to be at the Entry and Mid job levels.",style={'marginLeft': '30px'}),
        html.Br(),html.Br(),
    ]),
    html.Div(children=[
        html.H3("Conclusion"),
        "The project successfully cleaned and visualized the dataset. Through this process, we:",
        html.Div("Ensured the data was clean, consistent, and analysis-ready.",style={'marginLeft': '30px'}),
        html.Div("Generated multiple visualizations to uncover patterns in job offers, salaries, and experience.",style={'marginLeft': '30px'}),
        html.Div("Built a foundation for further analysis, such as predictive modeling or career pathway optimization.",style={'marginLeft': '30px'}),
        html.Br(),html.Br(),
    ])
], className="bg-light p-4 m-2")
